#!/bin/bash
# Source function library.
. /etc/rc.d/init.d/functions

queryapi_HOME=/home/ec2-user/queryapi
exec="$queryapi_HOME/bin/run_queryapi.sh"
LOCK="/var/lock/subsys/queryapi"
export queryapi_HOME

RETVAL=0

pid_of_queryapi() {
    pgrep -f "java.*queryapi"
}

start() {

    echo -n $"Starting queryapi: "

    cd "$queryapi_HOME"
    $exec > /dev/null 2>&1 &
    pid_of_queryapi > /dev/null
    echo
    [ $RETVAL -eq 0 ] && touch $LOCK && (success $"$STRING" || failure $"$STRING")

    return $RETVAL
}

stop() {
    echo -n $"Stopping queryapi: "
    pid=`pid_of_queryapi`
   kill $pid
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $LOCK
    return $retval
}


status() {
    pid=`pid_of_queryapi`
    if [ -n "$pid" ]; then
        echo "queryapi (pid $pid) is running..."
        return 0
    fi
    if [ -f "$LOCK" ]; then
        echo $"${base} dead but subsys locked"
        return 2
    fi
    echo "queryapi is stopped"
    return 3
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL