---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[eventstore::default]
    attributes: {module: {name: "queryapi",path: "/home/vagrant/queryapi",executable_path: "/home/vagrant/queryapi/bin/run_queryapi.sh"}}
