---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[eventstore::collector]
      - recipe[eventstore::field_mapper]
      - recipe[eventstore::bad_event_logger]
      - recipe[eventstore::queryapi]
    attributes: {user: "vagrant"}
