---
driver:
  name: vagrant
# driver:
#   name: ec2
#   region: us-east-1
#   require_chef_omnibus: true
#   instance_type: t2.micro
#   aws_ssh_key_id: espoc
#   security_group_ids: ["espoc-services"]

# transport:
#   ssh_key: /Users/aravindh/.ssh/espoc
#   connection_timeout: 10
#   connection_retries: 5
#   username: ec2-user

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65

suites:
  - name: default
    run_list:
      - role[java]
      - recipe[collector::default]
    attributes:
